<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FinanceControl.Culture</RootNamespace>
    <AssemblyName>FinanceControl.Culture</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceControl.Contracts\FinanceControl.Contracts.csproj" />
  </ItemGroup>

</Project>
