$strings = [ordered]@{
  'AppName' = @('Cashly','Cashly','Cashly')
  'Common.Save' = @('Salvar alterações','Save changes','Guardar cambios')
  'Common.SaveShort' = @('Salvar','Save','Guardar')
  'Common.Cancel' = @('Cancelar','Cancel','Cancelar')
  'Common.Filter' = @('Filtrar','Filter','Filtrar')
  'Common.Edit' = @('Editar','Edit','Editar')
  'Common.Delete' = @('Excluir','Delete','Eliminar')
  'Common.Close' = @('Fechar','Close','Cerrar')
  'Common.Confirm' = @('Confirmar','Confirm','Confirmar')
  'Common.Ok' = @('OK','OK','OK')
  'Common.Select' = @('Selecione…','Select…','Seleccione…')
  'Common.All' = @('Todos','All','Todos')
  'Common.AllFem' = @('Todas','All','Todas')
  'Common.Actions' = @('Ações','Actions','Acciones')
  'Common.Search' = @('Buscar','Search','Buscar')
  'Common.Or' = @('ou','or','o')
  'Common.Day' = @('Dia {0}','Day {0}','Día {0}')
  'Common.Active' = @('Ativo','Active','Activo')
  'Common.Inactive' = @('Inativo','Inactive','Inactivo')
  'Common.Account' = @('Conta','Account','Cuenta')
  'Common.Category' = @('Categoria','Category','Categoría')
  'Common.User' = @('Usuário','User','Usuario')
  'Common.Copyright' = @('© 2026 Cashly. Todos os direitos reservados.','© 2026 Cashly. All rights reserved.','© 2026 Cashly. Todos los derechos reservados.')
  'Type.Income' = @('Receita','Income','Ingreso')
  'Type.Expense' = @('Despesa','Expense','Gasto')
  'Nav.Dashboard' = @('Dashboard','Dashboard','Panel')
  'Nav.Transactions' = @('Transações','Transactions','Transacciones')
  'Nav.Categories' = @('Categorias','Categories','Categorías')
  'Nav.PaymentMethods' = @('Meios de pagamento','Payment methods','Medios de pago')
  'Nav.Investments' = @('Investimentos','Investments','Inversiones')
  'Nav.Reports' = @('Relatórios','Reports','Informes')
  'Nav.ReportByPayment' = @('Relatório por meio pagamento','Report by payment method','Informe por medio de pago')
  'Nav.ReportByCategory' = @('Relatório por tipo categoria','Report by category','Informe por categoría')
  'Nav.ReportByTransactions' = @('Relatório de transações','Transaction report','Informe de transacciones')
  'Nav.Portfolio' = @('Navegação do portfólio','Portfolio navigation','Navegación del portafolio')
  'Nav.ReportsSubmenu' = @('Submenu de relatórios','Reports submenu','Submenú de informes')
  'Header.OpenMenu' = @('Abrir ou fechar menu','Open or close menu','Abrir o cerrar menú')
  'Header.CloseMenu' = @('Fechar menu','Close menu','Cerrar menú')
  'Header.Home' = @('Cashly — página inicial','Cashly — home page','Cashly — página de inicio')
  'Header.SearchPlaceholder' = @('Buscar páginas do sistema…','Search system pages…','Buscar páginas del sistema…')
  'Header.SearchLabel' = @('Buscar telas e menus','Search screens and menus','Buscar pantallas y menús')
  'Header.SearchEmpty' = @('Nenhuma página encontrada.','No pages found.','No se encontraron páginas.')
  'Header.Notifications' = @('Notificações','Notifications','Notificaciones')
  'Header.CloseNotifications' = @('Fechar notificações','Close notifications','Cerrar notificaciones')
  'Header.MarkAllRead' = @('Marcar todas como lidas','Mark all as read','Marcar todas como leídas')
  'Header.ViewAllNotifications' = @('Ver todas as notificações','View all notifications','Ver todas las notificaciones')
  'Header.NotificationsPanel' = @('Painel de notificações','Notifications panel','Panel de notificaciones')
  'Header.MyProfile' = @('Meu Perfil','My profile','Mi perfil')
  'Header.Settings' = @('Configurações','Settings','Configuración')
  'Header.Privacy' = @('Privacidade','Privacy','Privacidad')
  'Header.Logout' = @('Sair','Sign out','Salir')
  'Header.ProfileMenu' = @('Menu do perfil','Profile menu','Menú del perfil')
  'Home.Title' = @('Dashboard','Dashboard','Panel')
  'Home.TxSummary' = @('Resumo de transações','Transaction summary','Resumen de transacciones')
  'Home.TxSummarySub' = @('Visão consolidada dos seus últimos lançamentos.','Consolidated view of your latest entries.','Vista consolidada de sus últimos movimientos.')
  'Home.PeriodMonthly' = @('Mensal','Monthly','Mensual')
  'Home.PeriodWeekly' = @('Semanal','Weekly','Semanal')
  'Home.FilterTx' = @('Filtrar transações…','Filter transactions…','Filtrar transacciones…')
  'Home.FilterTxLabel' = @('Filtrar transações na tabela','Filter transactions in the table','Filtrar transacciones en la tabla')
  'Home.MoreFilters' = @('Mais filtros','More filters','Más filtros')
  'Home.OpenFilters' = @('Abrir filtros adicionais','Open additional filters','Abrir filtros adicionales')
  'Home.ColDate' = @('Data','Date','Fecha')
  'Home.ColDescription' = @('Descrição','Description','Descripción')
  'Home.ColCategory' = @('Categoria','Category','Categoría')
  'Home.ColValue' = @('Valor','Amount','Valor')
  'Home.SortByDate' = @('Ordenar por data','Sort by date','Ordenar por fecha')
  'Home.SortByDescription' = @('Ordenar por descrição','Sort by description','Ordenar por descripción')
  'Home.SortByCategory' = @('Ordenar por categoria','Sort by category','Ordenar por categoría')
  'Home.SortByValue' = @('Ordenar por valor','Sort by amount','Ordenar por valor')
  'Home.EmptyTx' = @('Nenhuma transação encontrada. Cadastre a primeira na tela de Transações ou ajuste os filtros.','No transactions found. Add the first one on the Transactions page or adjust the filters.','No se encontraron transacciones. Registre la primera en Transacciones o ajuste los filtros.')
  'Home.ShowingTx' = @('Mostrando {0} de {1} transações','Showing {0} of {1} transactions','Mostrando {0} de {1} transacciones')
  'Home.PrevPage' = @('Página anterior','Previous page','Página anterior')
  'Home.NextPage' = @('Próxima página','Next page','Página siguiente')
  'Home.PeriodIndicators' = @('Indicadores do período','Period indicators','Indicadores del período')
  'Home.PeriodSummary' = @('Período do resumo','Summary period','Período del resumen')
  'Home.MetricMonthlySpend' = @('Gasto total no mês','Total monthly spending','Gasto total del mes')
  'Home.MetricMonthlyIncome' = @('Receitas no mês','Monthly income','Ingresos del mes')
  'Home.MetricAccountBalance' = @('Saldo em contas','Account balance','Saldo en cuentas')
  'Home.TrendMonthlyExpenses' = @('Despesas no mês financeiro vigente','Expenses in the current financial month','Gastos del mes financiero vigente')
  'Home.TrendMonthlyIncome' = @('Entradas no mês financeiro vigente','Income in the current financial month','Entradas del mes financiero vigente')
  'Home.TrendAccountSum' = @('Soma do saldo atual das contas','Sum of current account balances','Suma del saldo actual de las cuentas')
  'Home.RegisterAccountHint' = @('Cadastre uma conta para começar','Register an account to get started','Registre una cuenta para comenzar')
  'Home.CurrentBalance' = @('Saldo atual das contas','Current account balance','Saldo actual de las cuentas')
  'Transactions.Title' = @('Transações','Transactions','Transacciones')
  'Transactions.Subtitle' = @('Histórico completo de movimentações financeiras.','Complete history of financial movements.','Historial completo de movimientos financieros.')
  'Transactions.New' = @('+ Nova transação','+ New transaction','+ Nueva transacción')
  'Transactions.Type' = @('Tipo','Type','Tipo')
  'Transactions.SearchPlaceholder' = @('Descrição, categoria ou meio de pagamento...','Description, category or payment method...','Descripción, categoría o medio de pago...')
  'Transactions.Empty' = @('Nenhuma transação encontrada. Cadastre a primeira com o botão acima ou ajuste os filtros.','No transactions found. Add the first one with the button above or adjust the filters.','No se encontraron transacciones. Registre la primera con el botón de arriba o ajuste los filtros.')
  'Transactions.Pagination' = @('Mostrando {0}–{1} de {2} transações','Showing {0}–{1} of {2} transactions','Mostrando {0}–{1} de {2} transacciones')
  'Transactions.MonthlyBalance' = @('Saldo mensal','Monthly balance','Saldo mensual')
  'Transactions.BiggestExpense' = @('Maior gasto','Biggest expense','Mayor gasto')
  'Transactions.BudgetAlert' = @('Alerta de orçamento','Budget alert','Alerta de presupuesto')
  'Transactions.EditTitle' = @('Editar transação','Edit transaction','Editar transacción')
  'Transactions.NewTitle' = @('Nova transação','New transaction','Nueva transacción')
  'Transactions.EditSub' = @('Altere os dados do lançamento','Change the entry details','Modifique los datos del movimiento')
  'Transactions.NewSub' = @('Registro de movimento de capital','Capital movement record','Registro de movimiento de capital')
  'Transactions.TxDate' = @('Data da transação','Transaction date','Fecha de la transacción')
  'Transactions.TxType' = @('Tipo de transação','Transaction type','Tipo de transacción')
  'Transactions.TxDescription' = @('Descrição do lançamento','Entry description','Descripción del movimiento')
  'Transactions.TxDescriptionPlaceholder' = @('Ex: Pagamento consultoria financeira','E.g.: Financial consulting payment','Ej.: Pago de consultoría financiera')
  'Transactions.PaymentMethod' = @('Meio de pagamento','Payment method','Medio de pago')
  'Transactions.Amount' = @('Valor','Amount','Valor')
  'Transactions.ConfirmEntry' = @('Confirmar lançamento','Confirm entry','Confirmar movimiento')
  'Transactions.DeleteConfirm' = @('Excluir esta transação?','Delete this transaction?','¿Eliminar esta transacción?')
  'Transactions.VsPreviousMonth' = @('vs mês anterior','vs previous month','vs mes anterior')
  'Transactions.BudgetShare' = @('Representa {0} do total de despesas filtradas.','Represents {0} of filtered expenses.','Representa {0} del total de gastos filtrados.')
  'Transactions.AmountWithCurrency' = @('Valor ({0})','Amount ({0})','Valor ({0})')
  'Transactions.TrendUp' = @('↑ {0}','↑ {0}','↑ {0}')
  'Transactions.TrendDown' = @('↓ {0}','↓ {0}','↓ {0}')
  'Transactions.NoBalanceChange' = @('Sem variação em relação ao mês anterior','No change from previous month','Sin variación respecto al mes anterior')
  'Transactions.NoPreviousMonthBalance' = @('Sem saldo no mês anterior para comparar','No balance in previous month to compare','Sin saldo en el mes anterior para comparar')
  'Transactions.BiggestExpenseHint' = @('{0} · {1}','{0} · {1}','{0} · {1}')
  'Categories.Title' = @('Categorias','Categories','Categorías')
  'Categories.Subtitle' = @('Cadastre categorias para classificar seus lançamentos. Receita ou despesa é definida na transação.','Register categories to classify your entries. Income or expense is defined in the transaction.','Registre categorías para clasificar sus movimientos. Ingreso o gasto se define en la transacción.')
  'Categories.New' = @('+ Nova categoria','+ New category','+ Nueva categoría')
  'Categories.SearchPlaceholder' = @('Nome da categoria...','Category name...','Nombre de la categoría...')
  'Categories.Empty' = @('Nenhuma categoria encontrada. Cadastre a primeira com o botão acima ou ajuste os filtros.','No categories found. Add the first one with the button above or adjust the filters.','No se encontraron categorías. Registre la primera con el botón de arriba o ajuste los filtros.')
  'Categories.Count' = @('{0} categoria(s)','{0} category(ies)','{0} categoría(s)')
  'Categories.DeleteConfirm' = @('Excluir esta categoria? Transações vinculadas impedem a exclusão.','Delete this category? Linked transactions prevent deletion.','¿Eliminar esta categoría? Las transacciones vinculadas impiden la eliminación.')
  'PaymentMethods.Title' = @('Meios de pagamento','Payment methods','Medios de pago')
  'PaymentMethods.Subtitle' = @('Cadastre formas de pagamento para usar nos lançamentos.','Register payment methods to use in entries.','Registre formas de pago para usar en los movimientos.')
  'PaymentMethods.New' = @('+ Novo meio de pagamento','+ New payment method','+ Nuevo medio de pago')
  'PaymentMethods.DeleteConfirm' = @('Excluir este meio de pagamento?','Delete this payment method?','¿Eliminar este medio de pago?')
  'PaymentMethods.SearchPlaceholder' = @('Nome ou código...','Name or code...','Nombre o código...')
  'PaymentMethods.Empty' = @('Nenhum meio de pagamento encontrado. Cadastre o primeiro com o botão acima ou ajuste os filtros.','No payment methods found. Add the first one with the button above or adjust the filters.','No se encontraron medios de pago. Registre el primero con el botón de arriba o ajuste los filtros.')
  'PaymentMethods.Count' = @('{0} meio(s) de pagamento','{0} payment method(s)','{0} medio(s) de pago')
  'Settings.Title' = @('Configurar conta','Account settings','Configurar cuenta')
  'Settings.PageTitle' = @('Configurações da conta','Account settings','Configuración de la cuenta')
  'Settings.PageSub' = @('Personalize sua experiência: preferências financeiras, notificações, aparência e segurança da conta.','Customize your experience: financial preferences, notifications, appearance and account security.','Personalice su experiencia: preferencias financieras, notificaciones, apariencia y seguridad de la cuenta.')
  'Settings.NavPreferences' = @('Preferências','Preferences','Preferencias')
  'Settings.NavNotifications' = @('Notificações','Notifications','Notificaciones')
  'Settings.NavAppearance' = @('Aparência','Appearance','Apariencia')
  'Settings.NavSecurity' = @('Segurança','Security','Seguridad')
  'Settings.NavPrivacy' = @('Privacidade e dados','Privacy and data','Privacidad y datos')
  'Settings.NavDanger' = @('Zona de perigo','Danger zone','Zona de peligro')
  'Settings.FinancialTitle' = @('Preferências financeiras','Financial preferences','Preferencias financieras')
  'Settings.FinancialSub' = @('Como os valores e datas aparecem em todo o sistema.','How amounts and dates appear throughout the system.','Cómo aparecen los valores y fechas en todo el sistema.')
  'Settings.Currency' = @('Moeda','Currency','Moneda')
  'Settings.Language' = @('Idioma','Language','Idioma')
  'Settings.DateFormat' = @('Formato de data','Date format','Formato de fecha')
  'Settings.FinancialMonthStart' = @('Início do mês financeiro','Financial month start','Inicio del mes financiero')
  'Settings.CurrencyBRL' = @('Real brasileiro (R$)','Brazilian real (R$)','Real brasileño (R$)')
  'Settings.CurrencyUSD' = @('Dólar americano (US$)','US dollar (US$)','Dólar estadounidense (US$)')
  'Settings.CurrencyEUR' = @('Euro (EUR)','Euro (EUR)','Euro (EUR)')
  'Settings.LanguagePt' = @('Português (Brasil)','Portuguese (Brazil)','Portugués (Brasil)')
  'Settings.LanguageEn' = @('English (US)','English (US)','Inglés (EE.UU.)')
  'Settings.LanguageEs' = @('Español','Spanish','Español')
  'Settings.DateDMY' = @('DD/MM/AAAA','DD/MM/YYYY','DD/MM/AAAA')
  'Settings.DateMDY' = @('MM/DD/AAAA','MM/DD/YYYY','MM/DD/YYYY')
  'Settings.DateYMD' = @('AAAA-MM-DD','YYYY-MM-DD','AAAA-MM-DD')
  'Settings.NotificationsTitle' = @('Notificações','Notifications','Notificaciones')
  'Settings.NotificationsSub' = @('Escolha o que deseja receber e quando.','Choose what you want to receive and when.','Elija qué desea recibir y cuándo.')
  'Settings.NotifMonthlySummary' = @('Resumo mensal por e-mail','Monthly email summary','Resumen mensual por correo')
  'Settings.NotifMonthlySummaryDesc' = @('Receba um panorama das suas receitas e despesas no fim de cada mês.','Receive an overview of your income and expenses at the end of each month.','Reciba un panorama de sus ingresos y gastos al final de cada mes.')
  'Settings.NotifHighSpending' = @('Alertas de gastos altos','High spending alerts','Alertas de gastos elevados')
  'Settings.NotifHighSpendingDesc' = @('Avisamos quando uma despesa ultrapassar o valor médio das suas categorias.','We notify you when an expense exceeds the average for your categories.','Le avisamos cuando un gasto supere el promedio de sus categorías.')
  'Settings.NotifBillReminders' = @('Lembretes de contas a pagar','Bill payment reminders','Recordatorios de cuentas por pagar')
  'Settings.NotifBillRemindersDesc' = @('Notificações sobre vencimentos próximos para você não esquecer.','Notifications about upcoming due dates so you do not forget.','Notificaciones sobre vencimientos próximos para que no olvide.')
  'Settings.NotifNewsTips' = @('Novidades e dicas','News and tips','Novedades y consejos')
  'Settings.NotifNewsTipsDesc' = @('Conteúdos e atualizações sobre novos recursos do Cashly.','Content and updates about new Cashly features.','Contenidos y actualizaciones sobre nuevas funciones de Cashly.')
  'Settings.AppearanceTitle' = @('Aparência','Appearance','Apariencia')
  'Settings.AppearanceSub' = @('Defina o tema visual da aplicação.','Set the visual theme of the application.','Defina el tema visual de la aplicación.')
  'Settings.Theme' = @('Tema','Theme','Tema')
  'Settings.ThemeDark' = @('🌙 Escuro','🌙 Dark','🌙 Oscuro')
  'Settings.ThemeLight' = @('☀️ Claro','☀️ Light','☀️ Claro')
  'Settings.ThemeAuto' = @('🖥️ Automático','🖥️ Automatic','🖥️ Automático')
  'Settings.SecurityTitle' = @('Segurança','Security','Seguridad')
  'Settings.SecuritySub' = @('Proteja o acesso à sua conta.','Protect access to your account.','Proteja el acceso a su cuenta.')
  'Settings.ChangePassword' = @('Alterar senha','Change password','Cambiar contraseña')
  'Settings.AccessPassword' = @('Senha de acesso','Access password','Contraseña de acceso')
  'Settings.AccessPasswordDesc' = @('Altere sua senha periodicamente para manter a conta segura.','Change your password periodically to keep your account secure.','Cambie su contraseña periódicamente para mantener su cuenta segura.')
  'Settings.TwoFactor' = @('Autenticação em duas etapas (2FA)','Two-factor authentication (2FA)','Autenticación en dos pasos (2FA)')
  'Settings.TwoFactorDesc' = @('Adicione uma camada extra de proteção ao fazer login.','Add an extra layer of protection when signing in.','Añada una capa extra de protección al iniciar sesión.')
  'Settings.EndSessions' = @('Encerrar sessões','End sessions','Cerrar sesiones')
  'Settings.EndSessionsDesc' = @('Desconecte sua conta de todos os dispositivos, incluindo este.','Disconnect your account from all devices, including this one.','Desconecte su cuenta de todos los dispositivos, incluido este.')
  'Settings.PrivacyPolicy' = @('Política de Privacidade','Privacy Policy','Política de Privacidad')
  'Settings.PrivacyPolicyDesc' = @('Saiba como coletamos, usamos e protegemos seus dados.','Learn how we collect, use and protect your data.','Sepa cómo recopilamos, usamos y protegemos sus datos.')
  'Settings.DeleteAccountDesc' = @('Remove permanentemente sua conta e todos os dados financeiros associados. Informe sua senha para confirmar.','Permanently removes your account and all associated financial data. Enter your password to confirm.','Elimina permanentemente su cuenta y todos los datos financieros asociados. Ingrese su contraseña para confirmar.')
  'Settings.PrivacyTitle' = @('Privacidade e dados','Privacy and data','Privacidad y datos')
  'Settings.PrivacySub' = @('Controle como seus dados são tratados.','Control how your data is handled.','Controle cómo se tratan sus datos.')
  'Settings.ViewPolicy' = @('Ver política','View policy','Ver política')
  'Settings.DangerTitle' = @('Zona de perigo','Danger zone','Zona de peligro')
  'Settings.DangerSub' = @('Ações permanentes que não podem ser desfeitas.','Permanent actions that cannot be undone.','Acciones permanentes que no se pueden deshacer.')
  'Settings.DeleteAccount' = @('Excluir conta','Delete account','Eliminar cuenta')
  'Settings.Password' = @('Senha','Password','Contraseña')
  'Settings.PasswordPlaceholder' = @('Digite sua senha atual','Enter your current password','Ingrese su contraseña actual')
  'Settings.DeleteAccountConfirm' = @('Tem certeza que deseja excluir sua conta? Todos os seus dados financeiros serão removidos permanentemente e esta ação não pode ser desfeita.','Are you sure you want to delete your account? All your financial data will be permanently removed and this action cannot be undone.','¿Está seguro de que desea eliminar su cuenta? Todos sus datos financieros se eliminarán permanentemente y esta acción no se puede deshacer.')
  'Settings.EndSessionsConfirm' = @('Desconectar sua conta de todos os dispositivos? Você precisará fazer login novamente.','Disconnect your account from all devices? You will need to log in again.','¿Desconectar su cuenta de todos los dispositivos? Deberá iniciar sesión nuevamente.')
  'Auth.LoginTitle' = @('Entrar','Sign in','Iniciar sesión')
  'Auth.LoginHero' = @('Controle suas {0} com precisão.','Control your {0} with precision.','Controle sus {0} con precisión.')
  'Auth.LoginHeroAccent' = @('finanças','finances','finanzas')
  'Auth.LoginHeroSub' = @('Gerencie receitas, despesas e categorias em um só lugar. Simples, rápido e seguro.','Manage income, expenses and categories in one place. Simple, fast and secure.','Gestione ingresos, gastos y categorías en un solo lugar. Simple, rápido y seguro.')
  'Auth.FeatureReports' = @('Relatórios e dashboards em tempo real','Real-time reports and dashboards','Informes y paneles en tiempo real')
  'Auth.FeatureCategories' = @('Categorize receitas e despesas facilmente','Easily categorize income and expenses','Categorice ingresos y gastos fácilmente')
  'Auth.FeatureSecurity' = @('Seus dados sempre protegidos','Your data always protected','Sus datos siempre protegidos')
  'Auth.WelcomeBack' = @('Bem-vindo de volta','Welcome back','Bienvenido de nuevo')
  'Auth.SignInTitle' = @('Entre na sua conta','Sign in to your account','Inicie sesión en su cuenta')
  'Auth.SignInSub' = @('Acesse seu painel e continue no controle das suas finanças.','Access your dashboard and stay in control of your finances.','Acceda a su panel y mantenga el control de sus finanzas.')
  'Auth.Email' = @('Email','Email','Correo electrónico')
  'Auth.EmailPlaceholder' = @('seu@email.com','you@email.com','tu@email.com')
  'Auth.Password' = @('Senha','Password','Contraseña')
  'Auth.PasswordPlaceholder' = @('sua senha','your password','su contraseña')
  'Auth.PasswordWeak' = @('Fraca','Weak','Débil')
  'Auth.PasswordMedium' = @('Média','Medium','Media')
  'Auth.PasswordGood' = @('Boa','Good','Buena')
  'Auth.PasswordStrong' = @('Forte','Strong','Fuerte')
  'Auth.SignIn' = @('Entrar','Sign in','Iniciar sesión')
  'Auth.CreateAccount' = @('Criar uma conta','Create an account','Crear una cuenta')
  'Auth.RegisterTitle' = @('Cadastre-se','Sign up','Registrarse')
  'Auth.RegisterHero' = @('Crie sua conta e controle suas {0}.','Create your account and control your {0}.','Cree su cuenta y controle sus {0}.')
  'Auth.RegisterHeroSub' = @('Cadastre-se gratuitamente e comece a gerenciar receitas, despesas e categorias em um só lugar. Simples, rápido e seguro.','Sign up for free and start managing income, expenses and categories in one place. Simple, fast and secure.','Regístrese gratis y comience a gestionar ingresos, gastos y categorías en un solo lugar. Simple, rápido y seguro.')
  'Auth.FeatureFree' = @('Cadastro rápido e 100% gratuito','Fast and 100% free registration','Registro rápido y 100% gratuito')
  'Auth.RegisterEyebrow' = @('Crie sua conta','Create your account','Cree su cuenta')
  'Auth.RegisterFormTitle' = @('Cadastre-se no Cashly','Sign up for Cashly','Regístrese en Cashly')
  'Auth.RegisterFormSub' = @('Leva menos de um minuto para começar.','It takes less than a minute to get started.','Tarda menos de un minuto en empezar.')
  'Profile.Title' = @('Meu perfil','My profile','Mi perfil')
  'Profile.Subtitle' = @('Visualize e atualize seus dados pessoais, foto e preferências de acesso.','View and update your personal data, photo and access preferences.','Visualice y actualice sus datos personales, foto y preferencias de acceso.')
  'Profile.NoUser' = @('Nenhum usuário encontrado. Cadastre-se ou verifique se a API está em execução.','No user found. Sign up or check if the API is running.','No se encontró usuario. Regístrese o verifique si la API está en ejecución.')
  'Profile.ChangePhoto' = @('Alterar foto','Change photo','Cambiar foto')
  'Profile.PhotoHint' = @('PNG ou JPG, até 2 MB.','PNG or JPG, up to 2 MB.','PNG o JPG, hasta 2 MB.')
  'Profile.AccountSettings' = @('Configurações da conta','Account settings','Configuración de la cuenta')
  'Profile.PersonalData' = @('Dados pessoais','Personal data','Datos personales')
  'Profile.PersonalDataSub' = @('Informações exibidas no sistema e usadas no login.','Information displayed in the system and used for login.','Información mostrada en el sistema y usada para iniciar sesión.')
  'Profile.Username' = @('Nome de usuário','Username','Nombre de usuario')
  'Profile.UsernamePlaceholder' = @('Seu nome','Your name','Su nombre')
  'Profile.ActiveAccount' = @('Conta ativa','Active account','Cuenta activa')
  'Profile.InactiveAccount' = @('Conta inativa','Inactive account','Cuenta inactiva')
  'Profile.PhotoAlt' = @('Foto de perfil','Profile photo','Foto de perfil')
  'Loading.Wait' = @('Aguarde','Please wait','Espere')
  'Reports.DayOfMonth' = @('Dia do mês','Day of month','Día del mes')
  'Reports.ByPaymentTitle' = @('Resumo por meio de pagamento','Summary by payment method','Resumen por medio de pago')
  'Reports.ByPaymentSubtitle' = @('Distribuição de receitas e despesas conforme os meios de pagamento cadastrados.','Distribution of income and expenses by registered payment methods.','Distribución de ingresos y gastos según los medios de pago registrados.')
  'Reports.ByCategoryTitle' = @('Resumo por categoria','Summary by category','Resumen por categoría')
  'Reports.ByCategorySubtitle' = @('Distribuição de receitas e despesas conforme suas categorias cadastradas.','Distribution of income and expenses by your registered categories.','Distribución de ingresos y gastos según sus categorías registradas.')
  'Reports.ExpensesByPayment' = @('Despesas por meio de pagamento','Expenses by payment method','Gastos por medio de pago')
  'Reports.ExpensesByPaymentSub' = @('Participação de cada meio no total de saídas.','Share of each method in total outflows.','Participación de cada medio en el total de salidas.')
  'Reports.ExpensesByCategory' = @('Despesas por categoria','Expenses by category','Gastos por categoría')
  'Reports.ExpensesByCategorySub' = @('Participação de cada categoria no total de saídas.','Share of each category in total outflows.','Participación de cada categoría en el total de salidas.')
  'Reports.IncomeVsExpenses' = @('Receitas vs despesas','Income vs expenses','Ingresos vs gastos')
  'Reports.IncomeVsExpensesSubPayment' = @('Comparativo dos principais meios de pagamento no período.','Comparison of main payment methods in the period.','Comparación de los principales medios de pago en el periodo.')
  'Reports.IncomeVsExpensesSubCategory' = @('Comparativo das principais categorias do período.','Comparison of main categories in the period.','Comparación de las principales categorías del periodo.')
  'Reports.DetailByPayment' = @('Detalhamento por meio de pagamento','Breakdown by payment method','Detalle por medio de pago')
  'Reports.DetailByCategory' = @('Detalhamento por categoria','Breakdown by category','Detalle por categoría')
  'Reports.DetailSub' = @('Valores absolutos e percentual sobre o total do mês.','Absolute values and percentage of the monthly total.','Valores absolutos y porcentaje sobre el total del mes.')
  'Reports.PaymentMethodColumn' = @('Meio de pagamento','Payment method','Medio de pago')
  'Reports.Period' = @('Período','Period','Período')
  'Reports.PeriodFilter' = @('Filtrar por mês','Filter by month','Filtrar por mes')
  'Reports.PeriodLabel' = @('Período: {0}','Period: {0}','Período: {0}')
  'Reports.PeriodWithCount' = @('Período: {0} · {1} transação(ões)','Period: {0} · {1} transaction(s)','Período: {0} · {1} transacción(es)')
  'Reports.PeriodTotals' = @('Totais do período','Period totals','Totales del periodo')
  'Reports.PeriodBalance' = @('Saldo do período','Period balance','Saldo del periodo')
  'Reports.Entries' = @('Lançamentos','Entries','Movimientos')
  'Reports.Balance' = @('Saldo','Balance','Saldo')
  'Reports.TransactionsCount' = @('Transações','Transactions','Transacciones')
  'Reports.ExpensePercent' = @('% despesas','% expenses','% gastos')
  'Reports.EmptyInPeriod' = @('Nenhuma transação encontrada em {0}.','No transactions found in {0}.','No se encontraron transacciones en {0}.')
  'Reports.EmptyHint' = @('Selecione outro mês ou cadastre transações para visualizar os gráficos.','Select another month or register transactions to view the charts.','Seleccione otro mes o registre transacciones para ver los gráficos.')
  'Reports.TxReportTitle' = @('Relatório de transações','Transaction report','Informe de transacciones')
  'Reports.TxReportSubtitle' = @('Visão consolidada dos lançamentos do período com gráficos e histórico detalhado.','Consolidated view of period entries with charts and detailed history.','Vista consolidada de los movimientos del periodo con gráficos e historial detallado.')
  'Reports.IncomeVsExpensesSub' = @('Proporção entre entradas e saídas no mês.','Ratio of inflows and outflows in the month.','Proporción entre entradas y salidas del mes.')
  'Reports.DailyMovement' = @('Movimento diário','Daily movement','Movimiento diario')
  'Reports.DailyMovementSub' = @('Receitas e despesas por dia do mês selecionado.','Income and expenses by day of the selected month.','Ingresos y gastos por día del mes seleccionado.')
  'Reports.TxHistory' = @('Histórico de transações','Transaction history','Historial de transacciones')
  'Reports.TxHistorySub' = @('Todos os lançamentos registrados no período.','All entries registered in the period.','Todos los movimientos registrados en el periodo.')
  'Reports.PaymentMethodCol' = @('Meio pagamento','Payment method','Medio de pago')
  'Reports.NoCategory' = @('Sem categoria','Uncategorized','Sin categoría')
  'Reports.NoPaymentMethod' = @('Sem meio de pagamento','No payment method','Sin medio de pago')
  'Reports.IncomeVsExpensesChart' = @('Gráfico receitas e despesas','Income and expenses chart','Gráfico de ingresos y gastos')
  'Reports.DailyChart' = @('Gráfico de movimento diário','Daily movement chart','Gráfico de movimiento diario')
  'Messages.ApiLoadPaymentMethods' = @('Não foi possível carregar meios de pagamento da API.','Could not load payment methods from the API.','No se pudieron cargar medios de pago de la API.')
  'Messages.ApiLoadCategories' = @('Não foi possível carregar categorias da API.','Could not load categories from the API.','No se pudieron cargar categorías de la API.')
  'Dialog.Info' = @('Informação','Information','Información')
  'Dialog.Success' = @('Sucesso','Success','Éxito')
  'Dialog.Error' = @('Atenção','Attention','Atención')
  'Dialog.ConfirmTitle' = @('Confirmar','Confirm','Confirmar')
  'Dialog.InvalidFileTitle' = @('Arquivo inválido','Invalid file','Archivo inválido')
  'Dialog.InvalidFileMessage' = @('A imagem deve ter no máximo 2 MB.','The image must be at most 2 MB.','La imagen debe tener como máximo 2 MB.')
  'Dialog.CurrentPasswordRequired' = @('Informe sua senha atual para continuar.','Enter your current password to continue.','Ingrese su contraseña actual para continuar.')
  'Messages.SettingsSaved' = @('Preferências financeiras salvas com sucesso.','Financial preferences saved successfully.','Preferencias financieras guardadas con éxito.')
  'Messages.SettingsSavedCurrency' = @('Preferências salvas. Valores convertidos para a nova moeda selecionada.','Preferences saved. Values converted to the newly selected currency.','Preferencias guardadas. Valores convertidos a la nueva moneda seleccionada.')
  'Messages.SettingsSaveError' = @('Não foi possível salvar as preferências financeiras. Tente novamente.','Could not save financial preferences. Please try again.','No se pudieron guardar las preferencias financieras. Inténtelo de nuevo.')
  'Messages.SessionsEnded' = @('Todas as sessões foram encerradas. Faça login novamente.','All sessions have been ended. Please sign in again.','Todas las sesiones se cerraron. Inicie sesión nuevamente.')
  'Messages.SessionsEndError' = @('Não foi possível encerrar as sessões. Tente novamente.','Could not end sessions. Please try again.','No se pudieron cerrar las sesiones. Inténtelo de nuevo.')
  'Messages.DeletePasswordRequired' = @('Informe sua senha para confirmar a exclusão da conta.','Enter your password to confirm account deletion.','Ingrese su contraseña para confirmar la eliminación de la cuenta.')
  'Messages.AccountDeleted' = @('Sua conta foi excluída permanentemente.','Your account has been permanently deleted.','Su cuenta fue eliminada permanentemente.')
  'Messages.DeleteAccountError' = @('Não foi possível excluir a conta. Tente novamente.','Could not delete account. Please try again.','No se pudo eliminar la cuenta. Inténtelo de nuevo.')
  'Messages.ApiLoadTxError' = @('Não foi possível carregar transações da API.','Could not load transactions from the API.','No se pudieron cargar transacciones de la API.')
  'Messages.ApiConnectError' = @('Não foi possível conectar à API. Verifique se o serviço está em execução.','Could not connect to the API. Check if the service is running.','No se pudo conectar a la API. Verifique si el servicio está en ejecución.')
  'Messages.TxDescriptionRequired' = @('Informe uma descrição (mín. 2 caracteres).','Enter a description (min. 2 characters).','Ingrese una descripción (mín. 2 caracteres).')
  'Messages.TxValueRequired' = @('Valor deve ser maior que zero.','Amount must be greater than zero.','El valor debe ser mayor que cero.')
  'Messages.TxCategoryRequired' = @('Selecione uma categoria.','Select a category.','Seleccione una categoría.')
  'Messages.TxCategoryInvalid' = @('Categoria inválida ou inativa.','Invalid or inactive category.','Categoría inválida o inactiva.')
  'Messages.TxPaymentRequired' = @('Selecione um meio de pagamento.','Select a payment method.','Seleccione un medio de pago.')
  'Messages.TxPaymentInvalid' = @('Meio de pagamento inválido.','Invalid payment method.','Medio de pago inválido.')
  'Messages.TxAccountUnavailable' = @('Conta da transação não disponível.','Transaction account not available.','Cuenta de la transacción no disponible.')
  'Messages.TxNotFound' = @('Transação não encontrada.','Transaction not found.','Transacción no encontrada.')
  'Messages.NameMinLength' = @('Nome deve ter pelo menos 2 caracteres.','Name must be at least 2 characters.','El nombre debe tener al menos 2 caracteres.')
  'Messages.PaymentMethodNotFound' = @('Meio de pagamento não encontrado.','Payment method not found.','Medio de pago no encontrado.')
  'Messages.BudgetNoTx' = @('Nenhuma transação nos filtros atuais.','No transactions in current filters.','No hay transacciones en los filtros actuales.')
  'Messages.BudgetNoExpense' = @('Nenhuma despesa nos filtros atuais.','No expenses in current filters.','No hay gastos en los filtros actuales.')
  'Messages.BudgetTopCategory' = @('Maior volume de despesas na categoria «{0}» (filtros atuais).','Highest expense volume in category «{0}» (current filters).','Mayor volumen de gastos en la categoría «{0}» (filtros actuales).')
  'Messages.BudgetRegisterTx' = @('Cadastre transações para acompanhar seu orçamento.','Register transactions to track your budget.','Registre transacciones para seguir su presupuesto.')
}

function Write-Resx($path, $index) {
  $settings = New-Object System.Xml.XmlWriterSettings
  $settings.Indent = $true
  $settings.Encoding = New-Object System.Text.UTF8Encoding($false)
  $writer = [System.Xml.XmlWriter]::Create($path, $settings)
  $writer.WriteStartDocument()
  $writer.WriteStartElement('root')
  foreach ($name in @('resmimetype','version','reader','writer')) {
    $writer.WriteStartElement('resheader')
    $writer.WriteAttributeString('name', $name)
    $writer.WriteStartElement('value')
    switch ($name) {
      'resmimetype' { $writer.WriteString('text/microsoft-resx') }
      'version' { $writer.WriteString('2.0') }
      'reader' { $writer.WriteString('System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') }
      'writer' { $writer.WriteString('System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') }
    }
    $writer.WriteEndElement()
    $writer.WriteEndElement()
  }
  foreach ($entry in $strings.GetEnumerator()) {
    $writer.WriteStartElement('data')
    $writer.WriteAttributeString('name', $entry.Key)
    $writer.WriteAttributeString('xml', 'space', $null, 'preserve')
    $writer.WriteStartElement('value')
    $writer.WriteString($entry.Value[$index])
    $writer.WriteEndElement()
    $writer.WriteEndElement()
  }
  $writer.WriteEndElement()
  $writer.WriteEndDocument()
  $writer.Close()
}

$base = Join-Path $PSScriptRoot '..\src\Presentation\FinanceControl.Web.App\Resources'
Write-Resx (Join-Path $base 'SharedResources.resx') 0
Write-Resx (Join-Path $base 'SharedResources.en-US.resx') 1
Write-Resx (Join-Path $base 'SharedResources.es-ES.resx') 2
Write-Host "Generated $($strings.Count) keys"
